// <auto-generated />
using System;
using BackendProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231204120029_addedCartWishlistModels")]
    partial class addedCartWishlistModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackendProject.Models.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3950),
                            Description = "There are many variations of passages of Lorem Ipsum available, majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly kn je believable There are manations of passages of Lorem Ipsum available, but the majority ahave suffered ami tar cholnay vulbo na alte ration. majority have suffered alteration in",
                            Image = "about.jpg",
                            SoftDeleted = false,
                            Title = "<h2>About <span>Christ</span></h2>",
                            VideoLink = "https://www.youtube.com/watch?v=7e90gBu4pas"
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("Adverts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3490),
                            Description = "<h1 class=\"white\"><span>Gifts</span>Christmas</h1>",
                            DirectionId = 1,
                            Image = "1.jpg",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3490),
                            Description = "<h2 class=\"black\"><span class=\"small\">Save <span class=\"red\">25%</span></span><span class=\"red\">Offer</span> Christmas</h2>",
                            DirectionId = 2,
                            Image = "2.jpg",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BackendProject.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2017, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney Colleg Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and goingthrough the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. Thisbook is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.",
                            SoftDeleted = false,
                            Title = "If you are going to use a passage latin at Hampdun."
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2020, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney Colleg Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and goingthrough the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. Thisbook is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.",
                            SoftDeleted = false,
                            Title = "If you are going to use a passage latin at Hampdun."
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2018, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
                            SoftDeleted = false,
                            Title = "If you are going to use a passage latin at Hampdun."
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
                            SoftDeleted = false,
                            Title = "If you are going to use a passage latin at Hampdun."
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
                            SoftDeleted = false,
                            Title = "If you are going to use a passage latin at Hampdun."
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2021, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
                            SoftDeleted = false,
                            Title = "If you are going to use a passage latin at Hampdun."
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2019, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
                            SoftDeleted = false,
                            Title = "If you are going to use a passage latin at Hampdun."
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2017, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
                            SoftDeleted = false,
                            Title = "If you are going to use a passage latin at Hampdun."
                        });
                });

            modelBuilder.Entity("BackendProject.Models.BlogImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3800),
                            Image = "1.jpg",
                            IsMain = true,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3800),
                            Image = "2.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3800),
                            Image = "3.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3810),
                            Image = "2.jpg",
                            IsMain = true,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            BlogId = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3810),
                            Image = "1.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            BlogId = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3810),
                            Image = "3.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            BlogId = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3820),
                            Image = "3.jpg",
                            IsMain = true,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            BlogId = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3820),
                            Image = "1.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            BlogId = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3820),
                            Image = "2.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            BlogId = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3820),
                            Image = "1.jpg",
                            IsMain = true,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            BlogId = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3820),
                            Image = "2.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            BlogId = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3830),
                            Image = "3.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            BlogId = 5,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3830),
                            Image = "2.jpg",
                            IsMain = true,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            BlogId = 5,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3830),
                            Image = "1.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            BlogId = 5,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3830),
                            Image = "3.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            BlogId = 6,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3840),
                            Image = "3.jpg",
                            IsMain = true,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            BlogId = 6,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3840),
                            Image = "1.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            BlogId = 6,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3840),
                            Image = "2.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            BlogId = 7,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3840),
                            Image = "2.jpg",
                            IsMain = true,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            BlogId = 7,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3850),
                            Image = "1.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 21,
                            BlogId = 7,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3850),
                            Image = "3.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 22,
                            BlogId = 8,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3850),
                            Image = "3.jpg",
                            IsMain = true,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 23,
                            BlogId = 8,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3850),
                            Image = "1.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 24,
                            BlogId = 8,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3860),
                            Image = "2.jpg",
                            IsMain = false,
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.BlogTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("TagId");

                    b.ToTable("BlogTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            TagId = 1
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 1,
                            TagId = 5
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 1,
                            TagId = 6
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 1,
                            TagId = 4
                        },
                        new
                        {
                            Id = 5,
                            BlogId = 2,
                            TagId = 1
                        },
                        new
                        {
                            Id = 6,
                            BlogId = 2,
                            TagId = 4
                        },
                        new
                        {
                            Id = 7,
                            BlogId = 2,
                            TagId = 3
                        },
                        new
                        {
                            Id = 8,
                            BlogId = 2,
                            TagId = 6
                        },
                        new
                        {
                            Id = 9,
                            BlogId = 3,
                            TagId = 1
                        },
                        new
                        {
                            Id = 10,
                            BlogId = 3,
                            TagId = 2
                        },
                        new
                        {
                            Id = 11,
                            BlogId = 3,
                            TagId = 5
                        },
                        new
                        {
                            Id = 12,
                            BlogId = 3,
                            TagId = 3
                        },
                        new
                        {
                            Id = 13,
                            BlogId = 4,
                            TagId = 1
                        },
                        new
                        {
                            Id = 14,
                            BlogId = 4,
                            TagId = 5
                        },
                        new
                        {
                            Id = 15,
                            BlogId = 4,
                            TagId = 6
                        },
                        new
                        {
                            Id = 16,
                            BlogId = 5,
                            TagId = 4
                        },
                        new
                        {
                            Id = 17,
                            BlogId = 5,
                            TagId = 1
                        },
                        new
                        {
                            Id = 18,
                            BlogId = 5,
                            TagId = 4
                        },
                        new
                        {
                            Id = 19,
                            BlogId = 6,
                            TagId = 3
                        },
                        new
                        {
                            Id = 20,
                            BlogId = 6,
                            TagId = 6
                        },
                        new
                        {
                            Id = 21,
                            BlogId = 6,
                            TagId = 1
                        },
                        new
                        {
                            Id = 22,
                            BlogId = 7,
                            TagId = 2
                        },
                        new
                        {
                            Id = 23,
                            BlogId = 7,
                            TagId = 5
                        },
                        new
                        {
                            Id = 24,
                            BlogId = 7,
                            TagId = 3
                        },
                        new
                        {
                            Id = 25,
                            BlogId = 8,
                            TagId = 6
                        },
                        new
                        {
                            Id = 26,
                            BlogId = 8,
                            TagId = 1
                        },
                        new
                        {
                            Id = 27,
                            BlogId = 8,
                            TagId = 2
                        },
                        new
                        {
                            Id = 28,
                            BlogId = 8,
                            TagId = 5
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3990),
                            Image = "1.png",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3990),
                            Image = "2.png",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3990),
                            Image = "3.png",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3990),
                            Image = "4.png",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(4000),
                            Image = "5.png",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(4000),
                            Image = "6.png",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BackendProject.Models.CartProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("BackendProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3560),
                            Name = "Decorations",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3570),
                            Name = "Outfits",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3570),
                            Name = "Candles",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3570),
                            Name = "Toys",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptiom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(4040),
                            Descriptiom = "It is a long established fact that readewill be distracted by the readable content of a page when looking at ilayout.",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(4050),
                            Email = "fidanbb@gmaill",
                            Message = "Helllooo",
                            Name = "Fidan Bashirova",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3540),
                            FullName = "Betty More",
                            Image = "1.jpg",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3540),
                            FullName = "Andy Morgan",
                            Image = "1.jpg",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3540),
                            FullName = "Sandra Black",
                            Image = "1.jpg",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3550),
                            FullName = "Mark White",
                            Image = "1.jpg",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3550),
                            FullName = "Lucy Western",
                            Image = "1.jpg",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "right"
                        },
                        new
                        {
                            Id = 2,
                            Name = "left"
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3590),
                            Description = "Desc1",
                            Name = "Holiday Candle",
                            Price = 35m,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3590),
                            Description = "Desc1",
                            Name = "Christmas Tree",
                            Price = 40m,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3620),
                            Description = "Desc1",
                            Name = "Santa Claus Doll",
                            Price = 30m,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3620),
                            Description = "Desc1",
                            Name = "Holiday Cap",
                            Price = 50m,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3630),
                            Description = "Desc1",
                            Name = "Holiday Doll",
                            Price = 60m,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3630),
                            Description = "Desc1",
                            Name = "Holiday Candle",
                            Price = 30m,
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3650),
                            Image = "1.jpg",
                            IsMain = true,
                            ProductId = 1,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3650),
                            Image = "2.jpg",
                            IsMain = false,
                            ProductId = 1,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3650),
                            Image = "2.jpg",
                            IsMain = true,
                            ProductId = 2,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3660),
                            Image = "3.jpg",
                            IsMain = false,
                            ProductId = 2,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3660),
                            Image = "3.jpg",
                            IsMain = true,
                            ProductId = 3,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3660),
                            Image = "4.jpg",
                            IsMain = false,
                            ProductId = 3,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3660),
                            Image = "4.jpg",
                            IsMain = true,
                            ProductId = 4,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3670),
                            Image = "5.jpg",
                            IsMain = false,
                            ProductId = 4,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3670),
                            Image = "5.jpg",
                            IsMain = true,
                            ProductId = 5,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3670),
                            Image = "6.jpg",
                            IsMain = false,
                            ProductId = 5,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3670),
                            Image = "6.jpg",
                            IsMain = true,
                            ProductId = 6,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3680),
                            Image = "2.jpg",
                            IsMain = false,
                            ProductId = 6,
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3510),
                            CustomerId = 1,
                            Message = "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system.",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3510),
                            CustomerId = 2,
                            Message = "I absolutely loved this product! It exceeded my expectations in every way. The quality is outstanding, and it arrived sooner than expected.",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3510),
                            CustomerId = 3,
                            Message = "Unfortunately, this item did not meet my expectations. The quality was subpar, and it didn't function as described. I'm quite disappointed with my purchase.",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3520),
                            CustomerId = 2,
                            Message = "I am extremely satisfied with this product! It not only met but exceeded my expectations. The quality is top-notch, and it has made a significant improvement in my daily life.",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3520),
                            CustomerId = 4,
                            Message = "The product has some great features, but there are a few drawbacks. While it's user-friendly and stylish, the battery life could be better. Overall, it's a good purchase with some room for improvement.",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3520),
                            CustomerId = 5,
                            Message = "I regret buying this item. It didn't live up to the hype, and the build quality is disappointing. I encountered issues shortly after purchase, and customer support was not helpful. Would not recommend..",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3700),
                            Key = "HeaderLogo",
                            SoftDeleted = false,
                            Value = "logo.png"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3700),
                            Key = "FooterLogo",
                            SoftDeleted = false,
                            Value = "footer-logo.png"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3700),
                            Key = "Address",
                            SoftDeleted = false,
                            Value = "ur address goes here,street Crossroad 123"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3700),
                            Key = "Phone",
                            SoftDeleted = false,
                            Value = "+99 859 658 589 . +69 587 456 25"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3710),
                            Key = "Eax",
                            SoftDeleted = false,
                            Value = "+55 784 7585 . + 985 698 586"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3710),
                            Key = "Email",
                            SoftDeleted = false,
                            Value = "christ@email.com"
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3330),
                            Description = "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which.",
                            Header = "Save 25%",
                            Image = "1.jpg",
                            SoftDeleted = false,
                            Title = "Christmas Sale"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3370),
                            Description = "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which.",
                            Header = "Save 25%",
                            Image = "2.jpg",
                            SoftDeleted = false,
                            Title = "Christmas Sale"
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Social", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Socials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(4010),
                            Name = "fa fa-facebook",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(4020),
                            Name = "fa fa-twitter",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(4020),
                            Name = "fa fa-instagram",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(4020),
                            Name = "fa fa-pinterest-p",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(4020),
                            Name = "fa fa-linkedin",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Subscribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Subscribes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3930),
                            Email = "fidanbb@gmail.com",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3930),
                            Email = "surac@gmail.com",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3930),
                            Email = "ismayil@gmail.com",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3930),
                            Email = "kubra@gmail.com",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3730),
                            Name = "Bestsellers",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3730),
                            Name = "Gifts",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3730),
                            Name = "New",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3740),
                            Name = "Christmas Gift",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3740),
                            Name = "Festive Cakes",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3740),
                            Name = "Home Decor",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3740),
                            Name = "Toys",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3960),
                            FullName = "Terry Soto",
                            Image = "1.jpg",
                            Position = "Ceo",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3970),
                            FullName = "Maria Lane",
                            Image = "2.jpg",
                            Position = "Marketer",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3970),
                            FullName = "Justin Evans",
                            Image = "3.jpg",
                            Position = "Developer",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 12, 4, 16, 0, 28, 420, DateTimeKind.Local).AddTicks(3970),
                            FullName = "Rose Dixon",
                            Image = "4.jpg",
                            Position = "Designer",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("BackendProject.Models.WishlistProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistProducts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BackendProject.Models.Advert", b =>
                {
                    b.HasOne("BackendProject.Models.Direction", "Direction")
                        .WithMany("Adverts")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("BackendProject.Models.BlogImage", b =>
                {
                    b.HasOne("BackendProject.Models.Blog", "Blog")
                        .WithMany("Images")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("BackendProject.Models.BlogTag", b =>
                {
                    b.HasOne("BackendProject.Models.Blog", "Blog")
                        .WithMany("BlogTags")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendProject.Models.Tag", "Tag")
                        .WithMany("BlogTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BackendProject.Models.Cart", b =>
                {
                    b.HasOne("BackendProject.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BackendProject.Models.CartProduct", b =>
                {
                    b.HasOne("BackendProject.Models.Cart", "Cart")
                        .WithMany("CartProducts")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendProject.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendProject.Models.Product", b =>
                {
                    b.HasOne("BackendProject.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BackendProject.Models.ProductImage", b =>
                {
                    b.HasOne("BackendProject.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendProject.Models.Review", b =>
                {
                    b.HasOne("BackendProject.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BackendProject.Models.Wishlist", b =>
                {
                    b.HasOne("BackendProject.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BackendProject.Models.WishlistProduct", b =>
                {
                    b.HasOne("BackendProject.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendProject.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistProducts")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BackendProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BackendProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BackendProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendProject.Models.Blog", b =>
                {
                    b.Navigation("BlogTags");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("BackendProject.Models.Cart", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("BackendProject.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BackendProject.Models.Customer", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BackendProject.Models.Direction", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("BackendProject.Models.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("BackendProject.Models.Tag", b =>
                {
                    b.Navigation("BlogTags");
                });

            modelBuilder.Entity("BackendProject.Models.Wishlist", b =>
                {
                    b.Navigation("WishlistProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
